import { FormControl, Validators } from '@angular/forms';

export const FormFieldsOperatingWindows = {
  id: new FormControl(null),
  name: new FormControl(null),
  cliente: new FormControl(null, [Validators.required]),
  zona_control: new FormControl(null, [Validators.required]),
  start_time_local:new FormControl(null, [Validators.required]),
  end_time_local: new FormControl(null, [Validators.required]),
  start_time: new FormControl(null, [Validators.required]),
  end_time: new FormControl(null, [Validators.required]),
  day_0: new FormControl(false),
  day_1: new FormControl(false),
  day_2: new FormControl(false),
  day_3: new FormControl(false),
  day_4: new FormControl(false),
  day_5: new FormControl(false),
  day_6: new FormControl(false),
  day_0_local: new FormControl(false),
  day_1_local: new FormControl(false),
  day_2_local: new FormControl(false),
  day_3_local: new FormControl(false),
  day_4_local: new FormControl(false),
  day_5_local: new FormControl(false),
  day_6_local: new FormControl(false),
  total_daily_capacity: new FormControl(),
  simultaneous_capacity: new FormControl(),
  min_expected_daily: new FormControl(),
  max_waiting_assets: new FormControl(),
  expected_attention_time: new FormControl(),
  min_permanence_time: new FormControl(),
  level_1_time_alert: new FormControl(),
  level_2_time_alert: new FormControl(),
  level_3_time_alert: new FormControl(),
  level_4_time_alert: new FormControl(),
  recaptcha: new FormControl()
};
